[package]
name = "wsharp_runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Runtime library for the W# programming language"

[dependencies]
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
